# This job listens for new releases and will build the appropriate artifacts
# and upload them to the release.

name: develop

on:
  push:
    branches:
      - develop
      - docker_arm64

permissions:
  contents: write

jobs:
  build-upload:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
